login: &login
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  reconnect: true

development:
  database: mystore_development
  <<: *login

test:
  database: mystore_test
  <<: *login

production:
  database: mystore_development
  <<: *login
